services:
  - type: web
    name: movie-match
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: TMDB_API_KEY
        sync: false # User will need to set this in the Render dashboard
      - key: PYTHON_VERSION
        value: 3.11.0
